pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  - name: isTagBuild
    value: ${{ startsWith(variables['Build.SourceBranch'],'refs/tags/') }}
  - name: imageTag
    value: ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
  - name: azureContainerRegistryConnection
    value: Keboola ACR
  - name: azureContainerRegistry
    value: keboola.azurecr.io
  - name: imageRepository_base
    value: docker-custom-python
  - name: imageRepository_mlflow
    value: docker-python-mlflow
  - name: imageRepository_databricks
    value: docker-python-databricks
  - name: imageRepository_snowpark
    value: docker-python-snowpark
  - name: changedProjects_python38
    value: 0
  - name: changedProjects_python310
    value: 0
  - name: changedProjects_pythonSnowpark
    value: 0


steps:
  - script: |
      ./bin/ci-find-changes.sh master \
        python38:python-3.8/ \
        python310:python-3.10/ \
        pythonSnowpark:python-snowpark/
    displayName: Find changes
    name: findChanges

  - script: docker buildx bake --load $(changedProjects)
    displayName: Build Docker images

# Push Quay
  - script: |
      set -Eeuo pipefail
      docker login -u="$(QUAY_USERNAME)" -p="$(QUAY_PASSWORD)" quay.io
      docker tag keboola/docker-custom-python:python-3.8 quay.io/keboola/$(imageRepository_base):python-3.8-$(imageTag)
      docker push -a quay.io/keboola/$(imageRepository_base)
    displayName: Push 3.8 image to quay.io
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_python38"], 1))

  - script: |
      set -Eeuo pipefail
      docker login -u="$(QUAY_USERNAME)" -p="$(QUAY_PASSWORD)" quay.io
      docker tag keboola/docker-custom-python:python-3.10 quay.io/keboola/$(imageRepository_base):python-3.10-$(imageTag)
      docker tag keboola/docker-custom-python:python-3.10 quay.io/keboola/$(imageRepository_base):latest
      docker push -a quay.io/keboola/$(imageRepository_base)
    displayName: Push 3.8 image to quay.io
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_python310"], 1))

# Push ACR
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(azureContainerRegistryConnection)
    condition: eq(variables['isTagBuild'], 'true')

  - script: |
      set -Eeuo pipefail
      docker tag keboola/docker-custom-python:python-3.8 $(azureContainerRegistry)/$(imageRepository_base):python-3.8-$(imageTag)
      docker push -a $(azureContainerRegistry)/$(imageRepository_base)
    displayName: Push 3.8 image to ACR
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_python38"], 1))

  - script: |
      set -Eeuo pipefail
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_base):python-3.10-$(imageTag)
      docker push -a $(azureContainerRegistry)/$(imageRepository_base)
      
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_mlflow):$(imageTag)
      docker push -a $(azureContainerRegistry)/$(imageRepository_mlflow)
      
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_databricks):$(imageTag)
      docker push -a $(azureContainerRegistry)/$(imageRepository_databricks)
    displayName: Push 3.10 images to ACR
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_python310"], 1))

  - script: |
      set -Eeuo pipefail
      docker tag keboola/docker-custom-python-snowpark $(azureContainerRegistry)/$(imageRepository_snowpark):$(imageTag)
      docker push -a $(azureContainerRegistry)/$(imageRepository_snowpark)
    displayName: Push python-snowpark image to ACR
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_pythonSnowpark"], 1))

# Push ECR
  - task: ECRPushImage@1
    inputs:
      awsCredentials: Production - ECR Distribution - MLFlow
      regionName: us-east-1
      sourceImageName: keboola/docker-custom-python
      sourceImageTag: python-3.10
      repositoryName: keboola/$(imageRepository_mlflow)
      pushTag: $(imageTag)
    displayName: Push $(imageRepository_mlflow) to ECR
    condition: and(eq(variables['isTagBuild'], 'true'), eq(variables["changedProjects_python310"], 1))

# Publish the latest tag info
  - script: printf "%s" "$(imageTag)" > base-python-artifact
    condition: eq(variables['isTagBuild'], 'true')
    displayName: Create artifact

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'base-python-artifact'
      artifact: 'keboola.docker-custom-python.latest-build'
    condition: eq(variables['isTagBuild'], 'true')
    displayName: 'Publish Tag Artifact'
