pool:
  vmImage: ubuntu-latest

variables:
  - name: imageTag
    value: ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
  - name: isTagBuild
    value: ${{ startsWith(variables['Build.SourceBranch'],'refs/tags/') }}
  - name: azureContainerRegistryConnection
    value: Keboola ACR
  - name: azureContainerRegistry
    value: keboola.azurecr.io
  - name: imageRepository_base
    value: docker-custom-python
  - name: imageRepository_mlflow
    value: docker-python-mlflow
  - name: imageRepository_databricks
    value: docker-python-databricks

trigger:
  - refs/tags/*

steps:
  - script: |
      ./bin/ci-find-changes.sh \
        python-3.8:python-3.8/ \
        python-3.10:python-3.10/
    displayName: Find changes
    name: findChanges

  - script: echo '##vso[task.setvariable variable=imageTag]$(Build.BuildId)'
    displayName: Set the imageTag to buildId if it's not a tag build
    condition: eq(variables['isTagBuild'], 'false')

  - script: docker buildx bake --load $(changedProjects)
    displayName: Build Docker images

# Push Quay
  - script: |
      set -Eeuo pipefail
      docker login -u="$(QUAY_USERNAME)" -p="$(QUAY_PASSWORD)" quay.io
      docker tag keboola/docker-custom-python:python-3.8 quay.io/keboola/$(imageRepository_base):python-3.8-$(imageTag)
      
      docker tag keboola/docker-custom-python:python-3.10 quay.io/keboola/$(imageRepository_base):python-3.10-$(imageTag)
      docker tag keboola/docker-custom-python:python-3.10 quay.io/keboola/$(imageRepository_base):latest
      
      docker push -a quay.io/keboola/$(imageRepository_base)
    displayName: Push images to quay.io
    condition: eq(variables['isTagBuild'], 'true')

# Push ACR
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(azureContainerRegistryConnection)
    condition: eq(variables['isTagBuild'], 'true')

  - script: |
      set -Eeuo pipefail
      docker tag keboola/docker-custom-python:python-3.8 $(azureContainerRegistry)/$(imageRepository_base):python-3.8-$(imageTag)
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_base):python-3.10-$(imageTag)
      
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_mlflow):$(imageTag)
      
      docker tag keboola/docker-custom-python:python-3.10 $(azureContainerRegistry)/$(imageRepository_databricks):$(imageTag)
      
      docker push -a $(azureContainerRegistry)/$(imageRepository_base)
    displayName: Push images to ACR
    condition: eq(variables['isTagBuild'], 'true')

# Push ECR
  - task: ECRPushImage@1
    inputs:
      awsCredentials: Production - ECR Distribution - MLFlow
      regionName: us-east-1
      sourceImageName: docker-custom-python
      sourceImageTag: python-3.10
      repositoryName: keboola/$(imageRepository_mlflow)
      pushTag: $(imageTag)
    displayName: Push $(imageRepository_mlflow) to ECR
    condition: eq(variables['isTagBuild'], 'true')

# Publish the latest tag info
  - script: printf "%s" "$(imageTag)" > base-python-artifact
    condition: eq(variables['isTagBuild'], 'true')
    displayName: Create artifact

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'base-python-artifact'
      artifact: 'keboola.docker-custom-python.latest-build'
    condition: eq(variables['isTagBuild'], 'true')
    displayName: 'Publish Tag Artifact'
